CREATE TABLE "election_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "election_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stationId" integer NOT NULL,
	"staffId" integer,
	"action" varchar(50) NOT NULL,
	"previousValue" integer,
	"newValue" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "election_staff" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "election_staff_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"username" varchar(100) NOT NULL,
	"passwordHash" varchar(256) NOT NULL,
	"role" varchar(50) DEFAULT 'staff' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "election_staff_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "election_station" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "election_station_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"location" varchar(256),
	"capacity" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "election_turnout" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "election_turnout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stationId" integer NOT NULL,
	"voterCount" integer DEFAULT 0 NOT NULL,
	"updatedBy" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "election_audit_log" ADD CONSTRAINT "election_audit_log_stationId_election_station_id_fk" FOREIGN KEY ("stationId") REFERENCES "public"."election_station"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "election_audit_log" ADD CONSTRAINT "election_audit_log_staffId_election_staff_id_fk" FOREIGN KEY ("staffId") REFERENCES "public"."election_staff"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "election_turnout" ADD CONSTRAINT "election_turnout_stationId_election_station_id_fk" FOREIGN KEY ("stationId") REFERENCES "public"."election_station"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_station_idx" ON "election_audit_log" USING btree ("stationId");--> statement-breakpoint
CREATE INDEX "staff_username_idx" ON "election_staff" USING btree ("username");--> statement-breakpoint
CREATE INDEX "station_name_idx" ON "election_station" USING btree ("name");--> statement-breakpoint
CREATE INDEX "turnout_station_idx" ON "election_turnout" USING btree ("stationId");